Add azure function for proxying results of classification
iruszpel/abandoned-miracles pull request #7
Opened 2023-01-06 19:08 UTC by iruszpel

2023-01-06 19:59 UTC, Klepackp approved these changes

2023-01-07 13:11 UTC, sobczal2 requested changes

2023-01-07 13:11 UTC, sobczal2 commented on functions/GetAnimalClassification/index.ts
> +  if (req.method === "GET") {
!== "POST"

2023-01-07 13:11 UTC, sobczal2 commented on functions/GetAnimalClassification/index.ts
> +  console.log(req.body.imageUrl);
usunąć

2023-01-07 13:11 UTC, sobczal2 commented on functions/GetAnimalClassification/index.ts
> +    console.log(response);
usunąć

2023-01-07 13:11 UTC, sobczal2 commented on functions/GetAnimalClassification/index.ts
> +  console.log(res?.[0]);
Usunąć

2023-01-07 13:23 UTC, sobczal2 approved these changes
Może być

2023-01-07 17:09 UTC, merged